/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  1: {
    YourContract: {
      address: "0xabad261d1f2ea43114fc22c55983c3b6ffee5cab",
      abi: [
        {
          type: "function",
          name: "credentialPubKeyX",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "credentialPubKeyY",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPasskeyAddress",
          inputs: [
            {
              name: "qx",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "qy",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "greeting",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "greetingSetter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerPasskey",
          inputs: [
            {
              name: "credentialId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "qx",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "qy",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registeredCredentials",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setGreetingWithPasskey",
          inputs: [
            {
              name: "_newGreeting",
              type: "string",
              internalType: "string",
            },
            {
              name: "credentialId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "auth",
              type: "tuple",
              internalType: "struct WebAuthn.WebAuthnAuth",
              components: [
                {
                  name: "r",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "s",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "challengeIndex",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "typeIndex",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "authenticatorData",
                  type: "bytes",
                  internalType: "bytes",
                },
                {
                  name: "clientDataJSON",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GreetingChangeWithPasskey",
          inputs: [
            {
              name: "credentialId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "newGreeting",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PasskeyRegistered",
          inputs: [
            {
              name: "credentialId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "qx",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "qy",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 23936055,
    },
  },
  31337: {
    YourContract: {
      address: "0xe1da8919f262ee86f9be05059c9280142cf23f48",
      abi: [
        {
          type: "function",
          name: "credentialPubKeyX",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "credentialPubKeyY",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPasskeyAddress",
          inputs: [
            {
              name: "qx",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "qy",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "greeting",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "greetingSetter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerPasskey",
          inputs: [
            {
              name: "credentialId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "qx",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "qy",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registeredCredentials",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setGreetingWithPasskey",
          inputs: [
            {
              name: "_newGreeting",
              type: "string",
              internalType: "string",
            },
            {
              name: "credentialId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "auth",
              type: "tuple",
              internalType: "struct WebAuthn.WebAuthnAuth",
              components: [
                {
                  name: "r",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "s",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "challengeIndex",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "typeIndex",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "authenticatorData",
                  type: "bytes",
                  internalType: "bytes",
                },
                {
                  name: "clientDataJSON",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GreetingChangeWithPasskey",
          inputs: [
            {
              name: "credentialId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "newGreeting",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PasskeyRegistered",
          inputs: [
            {
              name: "credentialId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "qx",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "qy",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 12,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
